version: '3.8'

services:
  mongodb:
    image: mongo:latest  # dernière version 
    container_name: mongodb_server
    ports:
      - "27017:27017"  # Mappe 
    volumes:
      - mongodb_data:/data/db  
      - mongodb_configdb:/data/configdb
volumes:
  mongodb_data:
  mongodb_configdb:
