apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.webdb.replicaCount }}
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb-container
        image: {{ .Values.webdb.image }} #oualghazi/flask-app:v4
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-0.mongodb-service-headless.moualghazi.svc.cluster.local:27017/
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"