version: '3.8'

services:
  # Flask app without DB connection
  flask-app-no-db:
    image: flask-img:latest
    container_name: flask-app-no-db
    environment:
      - FLASK_ENV=development
    networks:
      - flask-mongo-network
    ports:
      - "5001:5000"  
    restart: always

  # Flask app with DB connection
  flask-app-with-db:
    image: flask-app:v2
    container_name: flask-app-with-db
    networks:
      - flask-mongo-network
    ports:
      - "5002:5000"
    restart: always

  # NGINX Load Balancer
  nginx:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Optional if the file is named Dockerfile
    container_name: nginx-load-balancer
    ports:
      - "8080:80"  # Expose the custom NGINX load balancer
    networks:
      - flask-mongo-network
    depends_on:
      - flask-app-no-db
      - flask-app-with-db
    restart: always

  # MongoDB database
  mongodb:
    image: mongo:latest  # dernière version 
    container_name: mongo
    ports:
      - "27017:27017"  # Mappe
    volumes:
      - mongodb_data:/data/db
    networks:
      - flask-mongo-network
    restart: always

volumes:
  mongodb_data:

networks:
  flask-mongo-network:
    driver: bridge