apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb-deployment
  namespace: moualghazi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb-container
        image: oualghazi/flask-app:v4
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/ # Connexion à la base via KubeDNS
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"