version: '3.8'

services:
  flask-app:
    build:
      context: .
    image: flask-app:v2
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest  # dernière version 
    container_name: mongodb
    ports:
      - "27017:27017"  # Mappe
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  mongodb_data: